# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Modified Packages

on: pull_request

env:
  artifactRetentionDays: 14
  # Bump Node memory limit
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  build:
    name: Build the SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        # This makes Actions fetch all Git history so build-changed script can diff properly.
        fetch-depth: 0
    # Install Chrome so the correct version of webdriver can be installed by chromedriver when
    # setting up the repo. This must be done to build and execute Auth properly.
    - name: install Chrome stable
      run: |
        npx @puppeteer/browsers install chrome@stable
    - uses: actions/checkout@v3
    - name: Set up Node (20)
      uses: actions/setup-node@v3
      with:
        node-version: 22.10.0
    - name: Test setup and yarn install
      run: |
        cp config/ci.config.json config/project.json
        yarn
    - name: yarn build:changed core
      run: yarn build:changed core
    - name: Archive build
      if: ${{ !cancelled() }}
      run: |
        tar -cf build.tar --exclude=.git .
        gzip build.tar
    - name: Upload build archive
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v3
      with:
          name: build.tar.gz
          path: build.tar.gz
          retention-days: ${{ env.artifactRetentionDays }}

  test-chrome:
    name: Test Packages With Changed Files in Chrome and Node
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so run-changed script can diff properly.
          fetch-depth: 0
      - name: Set up Node (20)
        uses: actions/setup-node@v3
        with:
          node-version: 22.10.0
      - name: install Chrome stable
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: Download build archive
        uses: actions/download-artifact@v3
        with:
          name: build.tar.gz
      - name: Unzip build artifact
        run: tar xf build.tar.gz
      - name: Run tests on changed packages
        run: xvfb-run yarn test:changed core

  test-firefox:
    name: Test Packages With Changed Files in Firefox
    needs: build
    # Whatever version of Firefox comes with 22.04 is causing Firefox
    # startup to hang when launched by karma. Need to look further into
    # why.
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node (20)
        uses: actions/setup-node@v3
        with:
          node-version: 22.10.0
      - name: install Firefox stable
        run: |
          sudo apt-get update
          sudo apt-get install firefox
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: Download build archive
        uses: actions/download-artifact@v3
        with:
          name: build.tar.gz
      - name: Unzip build artifact
        run: tar xf build.tar.gz
      - name: Run tests on changed packages
        run: xvfb-run yarn test:changed core
        env:
          BROWSERS: 'Firefox'
          
          
  test-webkit:
    name: Test Packages With Changed Files in Webkit
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node (20)
        uses: actions/setup-node@v3
        with:
          node-version: 22.10.0
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
          npx playwright install webkit
      - name: Download build archive
        uses: actions/download-artifact@v3
        with:
          name: build.tar.gz
      - name: Unzip build artifact
        run: tar xf build.tar.gz
      - name: Run tests on changed packages
        run: yarn test:changed core
        env:
          BROWSERS: 'WebkitHeadless'